spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demodb?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password!